version: '3'
services:
  nginx-proxy:
    build: ./nginx-proxy
    image: nginx-proxy
    container_name: nginx-proxy-container
    ports:
      - "8080:80"
      - "4000:4000"
    volumes:
      - ./volumes/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
  bottle-app:
    build: ./bottle-app
    image: bottle-app
    container_name: bottle-app-container
    volumes:
      - ./volumes/bottle-app/:/opt/bottle-app/
  mysql-db:
    build: ./mysql-db
    image: mysql
    container_name: mysql-db-container
    volumes:
      - ./volumes/mysql-db/initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: mysql
  c-api:
    build: ./c-api
    image: c-api
    container_name: c-api-container
    volumes:
      - ./volumes/c-api/:/opt/