version: '3'
services:
  bottle-app:
    build: ./bottle-app
    image: bottle-app
    container_name: bottle-app-container
    ports:
      - "8080:80"
    volumes:
      - ./volumes/bottle-app/:/opt/bottle-app/